# theme: jekyll-theme-cayman
future: true
timezone: Europe/Stockholm
safe: true

title: pinguLib
# email: your-email@example.com
description: pinguLib css/js library - free library including javascripts and stylesheets

url: "https://pingu1337.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# twitter_username: jekyllrb
github_username:  pingu1337

permalink: :title 